platform :ios, '13'
use_frameworks! :linkage => :static

target 'Bugar' do

  pod 'Texture', :git => 'https://github.com/TextureGroup/Texture.git', :commit => '03e7d1f'

  target 'BugarTests' do
    inherit! :search_paths
    
  end

  target 'BugarUITests' do

  end

end
